In [15]:
import pandas as pd
from transformers import AutoTokenizer


df = pd.read_csv('Data_latih.csv')
display(df.head())

,ID,label,tanggal,judul,narasi,nama file gambar
0,71,1,17-Aug-20,Pemakaian Masker Menyebabkan Penyakit Legionna...,A caller to a radio talk show recently shared ...,71.jpg
1,461,1,17-Jul-20,Instruksi Gubernur Jateng tentang penilangan ...,Yth.Seluruh Anggota Grup Sesuai Instruksi Gube...,461.png
2,495,1,13-Jul-20,Foto Jim Rohn: Jokowi adalah presiden terbaik ...,Jokowi adalah presiden terbaik dlm sejarah ban...,495.png
3,550,1,8-Jul-20,"ini bukan politik, tapi kenyataan Pak Jokowi b...","Maaf Mas2 dan Mbak2, ini bukan politik, tapi k...",550.png
4,681,1,24-Jun-20,Foto Kadrun kalo lihat foto ini panas dingin,Kadrun kalo lihat foto ini panas dingin . .,681.jpg

In [8]:
df = df.rename(columns={
    'ID': 'record_id',
    'judul': 'title',
    'narasi': 'content',
    'tanggal': 'publication_date'
})

display(df.head())

,record_id,label,publication_date,title,content,nama file gambar
0,71,1,17-Aug-20,Pemakaian Masker Menyebabkan Penyakit Legionna...,A caller to a radio talk show recently shared ...,71.jpg
1,461,1,17-Jul-20,Instruksi Gubernur Jateng tentang penilangan ...,Yth.Seluruh Anggota Grup Sesuai Instruksi Gube...,461.png
2,495,1,13-Jul-20,Foto Jim Rohn: Jokowi adalah presiden terbaik ...,Jokowi adalah presiden terbaik dlm sejarah ban...,495.png
3,550,1,8-Jul-20,"ini bukan politik, tapi kenyataan Pak Jokowi b...","Maaf Mas2 dan Mbak2, ini bukan politik, tapi k...",550.png
4,681,1,24-Jun-20,Foto Kadrun kalo lihat foto ini panas dingin,Kadrun kalo lihat foto ini panas dingin . .,681.jpg

In [9]:
df = df.drop(columns=['nama file gambar', 'label'])
display(df.head())

,record_id,publication_date,title,content
0,71,17-Aug-20,Pemakaian Masker Menyebabkan Penyakit Legionna...,A caller to a radio talk show recently shared ...
1,461,17-Jul-20,Instruksi Gubernur Jateng tentang penilangan ...,Yth.Seluruh Anggota Grup Sesuai Instruksi Gube...
2,495,13-Jul-20,Foto Jim Rohn: Jokowi adalah presiden terbaik ...,Jokowi adalah presiden terbaik dlm sejarah ban...
3,550,8-Jul-20,"ini bukan politik, tapi kenyataan Pak Jokowi b...","Maaf Mas2 dan Mbak2, ini bukan politik, tapi k..."
4,681,24-Jun-20,Foto Kadrun kalo lihat foto ini panas dingin,Kadrun kalo lihat foto ini panas dingin . .

In [10]:
df = df[['record_id', 'title', 'content', 'publication_date']]
display(df.head())

,record_id,title,content,publication_date
0,71,Pemakaian Masker Menyebabkan Penyakit Legionna...,A caller to a radio talk show recently shared ...,17-Aug-20
1,461,Instruksi Gubernur Jateng tentang penilangan ...,Yth.Seluruh Anggota Grup Sesuai Instruksi Gube...,17-Jul-20
2,495,Foto Jim Rohn: Jokowi adalah presiden terbaik ...,Jokowi adalah presiden terbaik dlm sejarah ban...,13-Jul-20
3,550,"ini bukan politik, tapi kenyataan Pak Jokowi b...","Maaf Mas2 dan Mbak2, ini bukan politik, tapi k...",8-Jul-20
4,681,Foto Kadrun kalo lihat foto ini panas dingin,Kadrun kalo lihat foto ini panas dingin . .,24-Jun-20

In [11]:
text_columns = ['record_id', 'title', 'content', 'publication_date']
for col in text_columns:
    df[col] = df[col].apply(lambda x: x.lower() if isinstance(x, str) else x)
display(df.head())

,record_id,title,content,publication_date
0,71,pemakaian masker menyebabkan penyakit legionna...,a caller to a radio talk show recently shared ...,17-aug-20
1,461,instruksi gubernur jateng tentang penilangan ...,yth.seluruh anggota grup sesuai instruksi gube...,17-jul-20
2,495,foto jim rohn: jokowi adalah presiden terbaik ...,jokowi adalah presiden terbaik dlm sejarah ban...,13-jul-20
3,550,"ini bukan politik, tapi kenyataan pak jokowi b...","maaf mas2 dan mbak2, ini bukan politik, tapi k...",8-jul-20
4,681,foto kadrun kalo lihat foto ini panas dingin,kadrun kalo lihat foto ini panas dingin . .,24-jun-20

In [12]:
df['Status'] = 0

print(df)

      record_id                                              title  \
0            71  pemakaian masker menyebabkan penyakit legionna...
1           461  instruksi gubernur jateng tentang penilangan  ...
2           495  foto jim rohn: jokowi adalah presiden terbaik ...
3           550  ini bukan politik, tapi kenyataan pak jokowi b...
4           681       foto kadrun kalo lihat foto ini panas dingin
...         ...                                                ...
4226     999287  : kpk dilarang membawa brimob bersenjata masuk...
4227     999472            foto pejabat keuangan dibawah palu arit
4228     999501  gambar denny siregar musuh warga tasikmalaya d...
4229     999848  kaesang: bapak saya dengan kesederhaan bisa ni...
4230     999860  laser dari termometer gun akan merusak struktu...

                                                content publication_date  \
0     a caller to a radio talk show recently shared ...        17-aug-20
1     yth.seluruh anggota grup sesuai instruksi gube...        17-jul-20
2     jokowi adalah presiden terbaik dlm sejarah ban...        13-jul-20
3     maaf mas2 dan mbak2, ini bukan politik, tapi k...         8-jul-20
4           kadrun kalo lihat foto ini panas dingin . .        24-jun-20
...                                                 ...              ...
4226  kpk dilarang membawa brimob bersenjata masuk g...        17-jan-16
4227  jangan mau dialihkan kepada pakaian adat… foku...        20-aug-20
4228                 akhir nya bisa terkenal bang denny        17-aug-20
4229  bapak saya dengan kesederhaan bisa nipu rakyat...        21-jul-20
4230  in: saya nolak. kalau anda mau periksa, bukan ...        20-jul-20

      Status
0          0
1          0
2          0
3          0
4          0
...      ...
4226       0
4227       0
4228       0
4229       0
4230       0

[4231 rows x 5 columns]

In [14]:
df = df.iloc[1:].reset_index(drop=True)
df.to_csv('cleaned_data_hoax.csv', index=False)
display(df.tail())

,record_id,title,content,publication_date,Status
4224,999287,: kpk dilarang membawa brimob bersenjata masuk...,kpk dilarang membawa brimob bersenjata masuk g...,17-jan-16,0
4225,999472,foto pejabat keuangan dibawah palu arit,jangan mau dialihkan kepada pakaian adat… foku...,20-aug-20,0
4226,999501,gambar denny siregar musuh warga tasikmalaya d...,akhir nya bisa terkenal bang denny,17-aug-20,0
4227,999848,kaesang: bapak saya dengan kesederhaan bisa ni...,bapak saya dengan kesederhaan bisa nipu rakyat...,21-jul-20,0
4228,999860,laser dari termometer gun akan merusak struktu...,"in: saya nolak. kalau anda mau periksa, bukan ...",20-jul-20,0

In [17]:
cleaned_file_path = 'cleaned_data_hoax.csv'
df = pd.read_csv(cleaned_file_path)

columns_to_tokenize = ['title', 'content']

tokenizer = AutoTokenizer.from_pretrained("allenai/longformer-base-4096")

for column in columns_to_tokenize:
    df[f"{column}_tokens"] = df[column].apply(
        lambda x: tokenizer.tokenize(x) if pd.notnull(x) else []
    )
    df[f"{column}_token_ids"] = df[column].apply(
        lambda x: tokenizer.encode(x, truncation=True, max_length=512) if pd.notnull(x) else []
    )

tokenized_file_path = 'tokenized_data_hoax.csv'
df.to_csv(tokenized_file_path, index=False)
print(f"Tokenized data saved to {tokenized_file_path}")

Tokenized data saved to tokenized_data_hoax.csv

In [19]:
tokenized_df = pd.read_csv('tokenized_data_hoax.csv')
tokenized_df.tail()

,record_id,title,content,publication_date,Status,title_tokens,title_token_ids,content_tokens,content_token_ids
4224,999287,: kpk dilarang membawa brimob bersenjata masuk...,kpk dilarang membawa brimob bersenjata masuk g...,17-jan-16,0,"[':', 'Ġk', 'p', 'k', 'Ġd', 'ilar', 'ang', 'Ġm...","[0, 35, 449, 642, 330, 385, 16813, 1097, 26012...","['k', 'p', 'k', 'Ġd', 'ilar', 'ang', 'Ġmem', '...","[0, 330, 642, 330, 385, 16813, 1097, 26012, 42..."
4225,999472,foto pejabat keuangan dibawah palu arit,jangan mau dialihkan kepada pakaian adat… foku...,20-aug-20,0,"['f', 'oto', 'Ġpe', 'jab', 'at', 'Ġke', 'u', '...","[0, 506, 7087, 3723, 39805, 415, 7321, 257, 25...","['j', 'angan', 'Ġm', 'au', 'Ġdial', 'ih', 'kan...","[0, 267, 25750, 475, 1180, 11481, 4001, 11334,..."
4226,999501,gambar denny siregar musuh warga tasikmalaya d...,akhir nya bisa terkenal bang denny,17-aug-20,0,"['g', 'amb', 'ar', 'Ġd', 'enny', 'Ġs', 'ire', ...","[0, 571, 3146, 271, 385, 11867, 579, 1885, 627...","['akh', 'ir', 'Ġn', 'ya', 'Ġb', 'isa', 'Ġter',...","[0, 7352, 853, 295, 2636, 741, 6619, 8470, 694..."
4227,999848,kaesang: bapak saya dengan kesederhaan bisa ni...,bapak saya dengan kesederhaan bisa nipu rakyat...,21-jul-20,0,"['ka', 'es', 'ang', ':', 'Ġb', 'ap', 'ak', 'Ġs...","[0, 2348, 293, 1097, 35, 741, 1115, 677, 224, ...","['b', 'ap', 'ak', 'Ġsay', 'a', 'Ġden', 'gan', ...","[0, 428, 1115, 677, 224, 102, 3069, 3494, 449,..."
4228,999860,laser dari termometer gun akan merusak struktu...,"in: saya nolak. kalau anda mau periksa, bukan ...",20-jul-20,0,"['l', 'aser', 'Ġd', 'ari', 'Ġterm', 'ometer', ...","[0, 462, 12425, 385, 1512, 1385, 12687, 1751, ...","['in', ':', 'Ġsay', 'a', 'Ġn', 'ol', 'ak', '.'...","[0, 179, 35, 224, 102, 295, 1168, 677, 4, 449,..."